export function buildHelpText(): string {
  return [
    "Qlepa",
    "",
    "Главное:",
    "  pnpm start",
    "  npm run start",
    "",
    "Команды pnpm:",
    "  pnpm carousel --help",
    "  pnpm carousel start",
    "  pnpm carousel onboard",
    "  pnpm carousel doctor",
    "  pnpm carousel build <post-path>",
    "  pnpm carousel build <post-path> --watch",
    "  pnpm carousel preview <post-path>",
    "  pnpm carousel gen-photo <preset> <scene>",
    "  pnpm carousel render-test",
    "",
    "Если pnpm не установлен глобально:",
    "  npm run start",
    "  npm run carousel -- onboard",
    "  npm run carousel -- doctor",
    "  npm run carousel -- build posts/starter-post",
    "",
    "Что делают команды:",
    "  start                         Онбординг, проверка проекта и статус READY TO RUN.",
    "  onboard                       Показать список данных для первого запуска.",
    "  doctor                        Проверить локальные папки и приватные референсы.",
    "  build <post-path>              Собрать PNG-слайды для поста.",
    "  build <post-path> --watch      Пересобирать слайды при изменении post.md.",
    "  preview <post-path>            Открыть браузерное превью поста.",
    "  gen-photo <preset> <scene>     Подготовить промпт и путь для картинки.",
    "  render-test                    Собрать тестовую обложку.",
    "",
    "Важно:",
    "  Картинки генерируются полуавтоматически: команда готовит промпт и путь,",
    "  вы сохраняете исходную картинку в assets/generated/, затем проект рендерит финальные PNG.",
  ].join("\n");
}
